# Generated by Django 3.1.6 on 2021-02-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('starts', models.IntegerField()),
                ('sire', models.CharField(max_length=150)),
                ('dam', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=250)),
                ('trainer', models.CharField(max_length=150)),
                ('outcomes', models.CharField(choices=[('W', 'Win'), ('P', 'Place'), ('S', 'Show')], max_length=1)),
            ],
        ),
    ]
