# Generated by Django 3.1.6 on 2021-02-03 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('host_track', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('field_size', models.IntegerField()),
                ('grade', models.CharField(choices=[('G1', 'GRADE ONE'), ('G2', 'GRADE TWO'), ('G3', 'GRADE THREE')], max_length=2)),
                ('distance', models.CharField(max_length=200)),
                ('race_date', models.DateField()),
                ('entries', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='horse',
            name='race',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.race'),
        ),
    ]
