# Generated by Django 3.1.6 on 2021-02-03 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210203_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jockey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('starts', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Most Recent Race')),
                ('outcome', models.CharField(choices=[('W', 'Win'), ('P', 'Place'), ('S', 'Show')], default='W', max_length=1)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='horse',
            name='outcomes',
        ),
        migrations.RemoveField(
            model_name='horse',
            name='race',
        ),
        migrations.DeleteModel(
            name='Race',
        ),
        migrations.AddField(
            model_name='outcome',
            name='horse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.horse'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='jockey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.jockey'),
        ),
        migrations.AddField(
            model_name='horse',
            name='jockeys',
            field=models.ManyToManyField(to='main_app.Jockey'),
        ),
    ]
