# Generated by Django 3.1.6 on 2021-02-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210203_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='jockey',
            name='bio',
            field=models.TextField(default='', max_length=500),
        ),
    ]
