# Generated by Django 3.1.6 on 2021-02-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210203_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='user_watchlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jockey',
            name='user_watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
