# Generated by Django 3.1.6 on 2021-02-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='horse',
            name='user_watchlist',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='user_watchlist',
        ),
    ]
