# Generated by Django 3.1.6 on 2021-02-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210205_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='jockeys',
        ),
        migrations.AddField(
            model_name='jockey',
            name='horses',
            field=models.ManyToManyField(to='main_app.Horse'),
        ),
    ]
