# Generated by Django 3.1.6 on 2021-02-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20210205_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
