# Generated by Django 3.1.6 on 2021-02-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20210205_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='name',
            field=models.CharField(default='Race Title', max_length=150),
        ),
    ]
